# Generated by Django 4.0.5 on 2022-06-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_tag_name_tag_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
