# Generated by Django 4.0.5 on 2022-06-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag_postmodel_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postmodel',
            table='postmodel',
        ),
    ]
