# Generated by Django 4.0.5 on 2022-06-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
