# Generated by Django 4.0.5 on 2022-06-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='tag_name',
            field=models.ManyToManyField(to='post.tagmodel'),
        ),
    ]
