# Generated by Django 4.0.5 on 2022-06-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_tagmodel_tagname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='tag_name',
            new_name='tag_names',
        ),
    ]
