# Generated by Django 4.0.5 on 2022-06-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_tagmodel_tagname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='tagname',
            new_name='tagnames',
        ),
    ]
