# Generated by Django 4.0.5 on 2022-06-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_tagname_tagmodel_tagnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='tagnames',
            new_name='tag_names',
        ),
    ]
