# Generated by Django 4.0.5 on 2022-06-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_tagnames_tagmodel_tag_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_names',
            field=models.CharField(choices=[('D', 'day'), ('S', 'sports'), ('F', 'food'), ('N', 'news')], max_length=20),
        ),
    ]
