# Generated by Django 4.0.5 on 2022-06-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_tagmodel_tag_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_names',
            field=models.CharField(max_length=20),
        ),
    ]
