# Generated by Django 4.0.5 on 2022-06-17 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='follow',
            field=models.ManyToManyField(related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='my_user_table',
        ),
        migrations.DeleteModel(
            name='follow',
        ),
    ]
